[project]
name = "symbol"
version = "0.0.1"
description = "A framework for symbolic data manipulation"
dependencies = [
    "orjson>=3.10.0",
    "graphviz>=0.20.0",
    "anyio>=4.4.0",
    "ruff>=0.4.0",
    "libcst>=1.2.0",
]
requires-python = ">=3.9"
license = {text = "MIT"}

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"