graph LR

    subgraph "Benefits"
        P[Reduced Memory Footprint] --> Q[Efficient Resource Usage];
        R[Improved Performance] --> S[Faster Access to Static Attributes];
        T[Stability] --> U[Predictable Behavior in Production];
        V[Clear Lifecycle Management] --> W[Defined State Transitions];
    end

    style P fill:#70f9e7,stroke:#333,stroke-width:2px,color:#000000;
    style R fill:#ac748e,stroke:#333,stroke-width:2px,color:#000000;
    style T fill:#b643f9,stroke:#333,stroke-width:2px,color:#FFFFFF;
    style V fill:#05ac1f,stroke:#333,stroke-width:2px,color:#FFFFFF;
