
graph TD
    subgraph "Memory-Aware Maturing Process #40;immute#40;#41;#41;"
        H[Symbol.metadata #40;DefDict#41;] --> I[Dynamic Key-Value Store];
        J[deep_del#40;#41;] --> K[Recursive Attribute Deletion];
        L[gc.collect#40;#41;] --> M[Explicit Garbage Collection];
        N[_apply_merge_strategy#40;#41;] --> O[Handles Attribute Overwrites];
    end

    style H fill:#592daf,stroke:#333,stroke-width:2px,color:#FFFFFF
    style J fill:#28db32,stroke:#333,stroke-width:2px,color:#000000
    style L fill:#b54446,stroke:#333,stroke-width:2px,color:#FFFFFF;
    style N fill:#67f134,stroke:#333,stroke-width:2px,color:#000000;
